{% set name = "requests-ratelimiter" %}
{% set version = "0.3.1" %}
{% set hash_val = "242363e9a37fd26251bce43983554ed1b600f66b9a4eacd8819bbbe96e3bd338" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - poetry
    - pip
  run:
    - python >=3.6,<4.0
    - pyrate-limiter >=2.3
    - requests >=2.20,<3.0

test:
  imports:
    - requests_ratelimiter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/JWCook/requests-ratelimiter
  summary: Rate-limiting for the requests library
  license: MIT
  license_file: LICENSE
  doc_url: https://requests-ratelimiter.readthedocs.io
  dev_url: https://github.com/JWCook/requests-ratelimiter

extra:
  recipe-maintainers:
    - jwcook
