{% set name = "requests-ratelimiter" %}
{% set version = "0.4.1" %}
{% set hash_val = "254a2565947517016a1dadba51d778d26639a7bbc4114445c667b6d46e899836" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - poetry
    - pip
  run:
    - python >=3.7,<4.0
    - pyrate-limiter >=2.8,<3.0
    - requests >=2.20

test:
  imports:
    - requests_ratelimiter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/JWCook/requests-ratelimiter
  summary: Easy rate-limiting for python requests
  license: MIT
  license_file: LICENSE
  doc_url: https://requests-ratelimiter.readthedocs.io
  dev_url: https://github.com/JWCook/requests-ratelimiter

extra:
  recipe-maintainers:
    - jwcook
