{% set name = "requests-ratelimiter" %}
{% set version = "0.4.0" %}
{% set hash_val = "4fcd71bd75488409329bb4e7baad8df98efec2c3a5d34ad4388d84cd35eeda8d" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - poetry
    - pip
  run:
    - python >=3.7,<4.0
    - pyrate-limiter >=2.8
    - requests >=2.20

test:
  imports:
    - requests_ratelimiter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/JWCook/requests-ratelimiter
  summary: Easy rate-limiting for python requests
  license: MIT
  license_file: LICENSE
  doc_url: https://requests-ratelimiter.readthedocs.io
  dev_url: https://github.com/JWCook/requests-ratelimiter

extra:
  recipe-maintainers:
    - jwcook
